<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_SimpleDI" Id="{dc9ae8c0-fa7b-41bf-ac96-a136837e08c8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK F_SimpleDI
VAR_INPUT
	b_Simple_Di_Input AT %I* :BOOL;
END_VAR
VAR_OUTPUT
	bSimpleDi_Out :BOOL;
END_VAR
VAR
	Timer:ton;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Timer(IN:=b_Simple_Di_Input,q=>bSimpleDi_Out);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>